import type { WeekMoodMatch } from "./types";

export const sampleWeeks: WeekMoodMatch[] = [
  {
    year: 2026,
    week: 17,
    startDate: "2026-04-20",
    endDate: "2026-04-26",
    score: 86,
    movieMood: {
      dark: 0.92,
      romantic: 0.08,
      energetic: 0.42,
      melancholic: 0.64,
      dreamy: 0.25,
      tense: 1,
      warm: 0.1,
    },
    musicMood: {
      dark: 0.78,
      romantic: 0.12,
      energetic: 0.58,
      melancholic: 0.7,
      dreamy: 0.3,
      tense: 1,
      warm: 0.15,
    },
    movies: [
      {
        title: "Cure",
        year: 1997,
        genres: ["Crime", "Horror", "Thriller"],
        keywords: ["serial killer", "hypnosis", "detective"],
        mood: {
          dark: 0.9,
          romantic: 0,
          energetic: 0.1,
          melancholic: 0.5,
          dreamy: 0.25,
          tense: 1,
          warm: 0,
        },
      },
      {
        title: "Possession",
        year: 1981,
        genres: ["Drama", "Horror"],
        keywords: ["marriage crisis", "obsession"],
        mood: {
          dark: 1,
          romantic: 0.15,
          energetic: 0.35,
          melancholic: 0.7,
          dreamy: 0.2,
          tense: 0.85,
          warm: 0,
        },
      },
    ],
    artists: [
      { name: "Chelsea Wolfe", playcount: 44, tags: ["darkwave", "doom metal", "folk"] },
      { name: "Nine Inch Nails", playcount: 38, tags: ["industrial", "rock", "dark"] },
      { name: "Have a Nice Life", playcount: 27, tags: ["shoegaze", "post-punk", "sad"] },
    ],
    highlights: ["horror + industrial", "tensao alta", "melancolia consistente"],
  },
  {
    year: 2026,
    week: 16,
    startDate: "2026-04-13",
    endDate: "2026-04-19",
    score: 62,
    movieMood: {
      dark: 0.2,
      romantic: 0.82,
      energetic: 0.22,
      melancholic: 0.58,
      dreamy: 0.7,
      tense: 0.1,
      warm: 1,
    },
    musicMood: {
      dark: 0.15,
      romantic: 0.45,
      energetic: 0.55,
      melancholic: 0.35,
      dreamy: 0.82,
      tense: 0.1,
      warm: 0.92,
    },
    movies: [
      {
        title: "In the Mood for Love",
        year: 2000,
        genres: ["Drama", "Romance"],
        keywords: ["unrequited love", "memory"],
        mood: {
          dark: 0.05,
          romantic: 1,
          energetic: 0,
          melancholic: 0.85,
          dreamy: 0.8,
          tense: 0,
          warm: 0.8,
        },
      },
    ],
    artists: [
      { name: "Cocteau Twins", playcount: 35, tags: ["dream pop", "shoegaze", "ethereal"] },
      { name: "Sade", playcount: 24, tags: ["soul", "romantic", "smooth"] },
    ],
    highlights: ["romance + dream pop", "calor afetivo", "baixa tensao"],
  },
  {
    year: 2026,
    week: 15,
    startDate: "2026-04-06",
    endDate: "2026-04-12",
    score: 41,
    movieMood: {
      dark: 0.1,
      romantic: 0.15,
      energetic: 1,
      melancholic: 0.12,
      dreamy: 0.28,
      tense: 0.52,
      warm: 0.6,
    },
    musicMood: {
      dark: 0.62,
      romantic: 0.08,
      energetic: 0.32,
      melancholic: 0.9,
      dreamy: 0.84,
      tense: 0.3,
      warm: 0.22,
    },
    movies: [
      {
        title: "Mad Max: Fury Road",
        year: 2015,
        genres: ["Action", "Adventure"],
        keywords: ["desert", "survival", "chase"],
        mood: {
          dark: 0.15,
          romantic: 0,
          energetic: 1,
          melancholic: 0.1,
          dreamy: 0.2,
          tense: 0.6,
          warm: 0.5,
        },
      },
    ],
    artists: [
      { name: "Slowdive", playcount: 31, tags: ["shoegaze", "dream pop", "melancholic"] },
      { name: "Grouper", playcount: 26, tags: ["ambient", "sad", "dreamy"] },
    ],
    highlights: ["semana dissonante", "acao nos filmes", "ambient na musica"],
  },
];
